<a href="https://colab.research.google.com/github/DevNicque/pos-datascience/blob/modulo_2/Numpy_Indexa%C3%A7%C3%A3o%2C_Fatiamento_e_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Indexação, Fatiamento e Broadcasting

**Disciplina**: Programação para Ciência dos Dados  
**Docentes**: Elloá B. Guedes e Tiago E. de Melo  
**Contato:** ebgcosta@uea.edu.br, tmelo@uea.edu.br  
**Github:** http://github.com/elloa/numpy

## Apresentação

Este notebook deverá ser utilizado para a prática dos conceitos relativos à biblioteca numpy.

In [3]:
# Reservado para importação de bibliotecas
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


## Parte 3.1 - Indexação, Fatiamento e Iteração

1. Considere o exemplo a seguir e resolva os asserts completando as informações faltantes

* Indexação: 

In [ ]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[2,2]

11

no fatiamento [i:f] se eu omitir o i quer dizer o, se omito o f ele quer dizer o len

In [ ]:
a[2,:]

array([ 9, 10, 11, 12])

In [ ]:
a[3,2] = 99
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 99, 16]])

situação específica: indexação em um arry unidmensional

In [ ]:
b = np.arange(9,16,1)
b

array([ 9, 10, 11, 12, 13, 14, 15])

indexando:

In [ ]:
b[-4]

12

In [ ]:
b[-len(b)]

9

assert é a maneira de checar, fazer testes unitários baseados em alguma informação

In [ ]:
 assert b[-len(b)] == b[0]

desafio:

In [ ]:
a = np.arrange(10,16)
assert len(a)
assert a[-1] == # complete
assert a[4] == # complete
assert a[-len(a)] == #complete
assert a[[1,3,4]] == # complete

**indexação mais complexa:**

2. Seja a matriz a seguir:
    
<img src="../img/matriz.png"/>

2.1. Realize a indexação que retorna o elemento 14  
2.2. Obtenha as duas primeiras linhas com o auxílio de fatiamento  
2.3. Obtenha a segunda columa mediante fatiamento  
2.4. Obtenha o primeiro e o terceiro elemento de todas as linhas  
2.5  Imprima cada linha da matriz  
2.6  Imprima cada elemento da matriz  

In [ ]:
 a = np.arange(10,19).reshape((3,3))

In [ ]:
assert a[??] == 14 # complete

In [ ]:
 a = np.arange(1,17).reshape((4,4))
 a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[1:3, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [ ]:
a[2,0]

9

subseleção de array so funciona para o tipo unidmensional, não para arrays de múltipla dimensão

trazendo múltiplos valores de um array unidmensional:

In [ ]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

foi pego um array bidmensional e passar antes dimensões triplas

tras os valores das posições 1, 5 e 7

In [ ]:
a[[1,5,7]]

array([2, 6, 8])

trazendo a mesma linha 2 vezes:

In [ ]:
a[[0,0]]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

Boleanos e condicionais:

* permitem checar quais elementos de um  ndarray satisfazem certas condições
* facilitam a seleção de partes do array
* base para implementar "consultas" do pandas
* indexação condicional
* permitem fazer a seleção de certas partes do array

*verifica booleanamente quais os valores na matriz que são maiores ou igauis a 7:*

In [ ]:
a >=7

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

*tras os valores da matriz que são maiores ou iguais a 7*

In [ ]:
a[a >= 7]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Parte 3.2 - Manipulação de dimensões

- Já utilizamos o reshape em diversas ocasiões
- Preocupação: assegurar que haja elementos suficientes
1. Crie uma matriz (3,4) de números aleatórios quaisquer
2. Obtenha uma versão unidimensional desta matriz
3. Obtenha a transposta desta matriz

**Manipulação de dimensões é poder jogar o array para que lhe favoreça em alguma situação**

* reshape (eu preciso saber se o array original contem todos os elementos que satisfazem essa nova dimensão)
* ravel, flatten
* transpose

~array que vai de 1 a 100 e seja bdminesional - uma matriz 10x10~

In [ ]:
a = np.random.randint(1,100,(10,10))

*reshape:*

se eu fizer sem atribuição ao array, ele não alterará, só criará uma cópia (POO)

In [ ]:
a = a.reshape((100,))
a

array([80, 14, 29, 31, 68, 35, 12, 28, 69, 72, 89, 54, 88, 67, 10, 47, 13,
       65,  7, 77, 92, 69, 40, 12, 59, 12, 65, 11,  4, 76, 45,  9, 19, 84,
       47, 92, 23, 92, 25,  2,  1,  1, 27,  1, 54, 10, 42, 65, 45, 91, 68,
       83,  6, 34, 32, 46, 61, 62, 97, 42, 23, 37, 45, 98, 51, 83, 49, 71,
       96, 42,  4, 95, 41, 67, 86, 24, 57, 48,  8, 84, 15, 19, 61, 47, 43,
       55, 81, 68, 61, 52,  8,  8, 48, 62, 37, 20, 62, 34, 25,  2])

fazendo 2 linhas com 50 elementos:

In [ ]:
a = a.reshape((2,50))
a

array([[80, 14, 29, 31, 68, 35, 12, 28, 69, 72, 89, 54, 88, 67, 10, 47,
        13, 65,  7, 77, 92, 69, 40, 12, 59, 12, 65, 11,  4, 76, 45,  9,
        19, 84, 47, 92, 23, 92, 25,  2,  1,  1, 27,  1, 54, 10, 42, 65,
        45, 91],
       [68, 83,  6, 34, 32, 46, 61, 62, 97, 42, 23, 37, 45, 98, 51, 83,
        49, 71, 96, 42,  4, 95, 41, 67, 86, 24, 57, 48,  8, 84, 15, 19,
        61, 47, 43, 55, 81, 68, 61, 52,  8,  8, 48, 62, 37, 20, 62, 34,
        25,  2]])

*O ravel e flatten - tornam multipla dimensão em uma*

*a diferança de um para o outro é a manipulação interna que o numpy faz, sendo o flatten mais eficiente*

*exemplo: funções muito utilizadas em redes neurais para linearizar uma matriz*

In [ ]:
a.ravel()

array([80, 14, 29, 31, 68, 35, 12, 28, 69, 72, 89, 54, 88, 67, 10, 47, 13,
       65,  7, 77, 92, 69, 40, 12, 59, 12, 65, 11,  4, 76, 45,  9, 19, 84,
       47, 92, 23, 92, 25,  2,  1,  1, 27,  1, 54, 10, 42, 65, 45, 91, 68,
       83,  6, 34, 32, 46, 61, 62, 97, 42, 23, 37, 45, 98, 51, 83, 49, 71,
       96, 42,  4, 95, 41, 67, 86, 24, 57, 48,  8, 84, 15, 19, 61, 47, 43,
       55, 81, 68, 61, 52,  8,  8, 48, 62, 37, 20, 62, 34, 25,  2])

In [ ]:
a.flatten()

array([80, 14, 29, 31, 68, 35, 12, 28, 69, 72, 89, 54, 88, 67, 10, 47, 13,
       65,  7, 77, 92, 69, 40, 12, 59, 12, 65, 11,  4, 76, 45,  9, 19, 84,
       47, 92, 23, 92, 25,  2,  1,  1, 27,  1, 54, 10, 42, 65, 45, 91, 68,
       83,  6, 34, 32, 46, 61, 62, 97, 42, 23, 37, 45, 98, 51, 83, 49, 71,
       96, 42,  4, 95, 41, 67, 86, 24, 57, 48,  8, 84, 15, 19, 61, 47, 43,
       55, 81, 68, 61, 52,  8,  8, 48, 62, 37, 20, 62, 34, 25,  2])

*fazendo a matriz transposta:*

In [ ]:
c = np.ones((2,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
c.transpose()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

*maneira pythonica de fazer matriz transposta:*

In [ ]:
c.T

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**Broadcasting**

* permite que um operador ou função atue em um ou mais arrays mesmo quando eles não possuem o mesmo shape
* Dois arrays estão sujeitos ao broadcasting quando todas as suas dimensões são compatíveis
*O comprimento de cada dimensão é igual 
* Ou um dos comprimentos é igaul a 1
*Regras: add 1 a cada dimensão faltante / a dimensão faltante é preenchida com réplicas dos valores

## Parte 3.3 - Broadcasting

1. Considere a matriz A e b dadas a seguir
2. Qual o resultado de A + b segundo as regras de broadcasting?
3. Qual seria o impacto se não tivéssemos as regras de broadcasting nesta biblioteca?

*o broadcasting acontece implicitamente dentro do numpy quando as dimensões dos arrays não compatíveis, e quando ao menos um deles tem 1 dimensão*

neste exemplo temos 2 arrays, o x com 5 dimensoes e y com 1 dimensao

In [4]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
y = np.ones((5,1))
y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

o resultado desta soma só foi possivel por causa da regra do broadcasting, pq em si não tem dados de y suficientes para somar com todos os elementos de x

ao somar ele transforma o array unidemensional em uma matriz do tamanho da qual ele precisa somar e preenche esta com a replicação da dimensão que ele tem

In [6]:
x+y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
a = np.arange(1,13,1).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
b = np.array([1,0,0,1])
b

array([1, 0, 0, 1])

In [9]:
a+b

array([[ 2,  2,  3,  5],
       [ 6,  6,  7,  9],
       [10, 10, 11, 13]])

**Biblioteca numpy - Arquivos**

* Possibilidade de leitura e escrita em arquivos
* Arquivos binários ou textuais
*np.ave e np.load
* Prática com imagens